### PR TITLE
Updated WARC bands + 4M

### PR DESCRIPTION
**Pull request by awandahl**
Added WARC bands + 4M

### CODE REVIEW

**Comment by awandahl** [comment]
Hoping that I have changed in all right places, and the correct ones too

**Comment by mbridak** [comment]
When I try and run your branch I get:

```python
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/PyQt6/uic/ui_file.py", line 35, in __init__
    document = ElementTree.parse(ui_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.12/xml/etree/ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: mismatched tag: line 287, column 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbridak/.local/bin/not1mm", line 5, in <module>
    from not1mm.__main__ import run
  File "/home/mbridak/.local/lib/python3.12/site-packages/not1mm/__main__.py", line 3545, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/home/mbridak/.local/lib/python3.12/site-packages/not1mm/__main__.py", line 193, in __init__
    uic.loadUi(fsutils.APP_DATA_PATH / "main.ui", self)
  File "/usr/lib64/python3.12/site-packages/PyQt6/uic/load_ui.py", line 86, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/PyQt6/uic/Loader/loader.py", line 62, in loadUi
    return self.parse(filename)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/PyQt6/uic/uiparser.py", line 995, in parse
    ui_file = UIFile(filename)
              ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/PyQt6/uic/ui_file.py", line 37, in __init__
    self._raise_exception("invalid Qt Designer file", detail=str(e))
  File "/usr/lib64/python3.12/site-packages/PyQt6/uic/ui_file.py", line 92, in _raise_exception
    raise UIFileException(self._ui_file, message, detail=detail)
PyQt6.uic.exceptions.UIFileException: /home/mbridak/.local/lib/python3.12/site-packages/not1mm/data/main.ui: invalid Qt Designer file: mismatched tag: line 287, column 12
```

Something is wrong with you ui file.

**Comment by awandahl** [comment]
Stupid of me not validating the XML

**Comment by awandahl** [comment]
Validated XML

**Comment by mbridak** [comment]
Now I get this:

```python
Traceback (most recent call last):
  File "/home/mbridak/.local/lib/python3.12/site-packages/not1mm/__main__.py", line 964, in edit_configuration_settings
    self.configuration_dialog = Settings(fsutils.APP_DATA_PATH, self.pref)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbridak/.local/lib/python3.12/site-packages/not1mm/lib/settings.py", line 28, in __init__
    self.setup()
  File "/home/mbridak/.local/lib/python3.12/site-packages/not1mm/lib/settings.py", line 99, in setup
    self.activate_60m.setChecked(bool("60" in self.preference.get("bands", [])))
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'activate_60m'. Did you mean: 'activate_10m'?

```

**Comment by awandahl** [comment]
Hmmm... beats me now, will look further. Found a few line breaks that look weird.

How about main.ui line 100. 160M CW has a <property name="accessibleName"> but no other bands.
```
 <widget class="QLabel" name="cw_band_160">
             <property name="accessibleName">
              <string>160 c w</string>
             </property>
             <property name="text">
              <string>160</string>
             </property>
```

**Comment by awandahl** [comment]
I have been a bit trigger happy before, but now this code works locally for me at least

**Comment by mbridak** [comment]
Hey! It didn't crash! I'll go ahead and merge it. Then fix up the Band Tab in the config dialog.
Thanks!

**Pull request merged**
